## name: CyberXero
## author: MurderFromMars
## license: GNU GPL
## upstream: https://github.com/MurderFromMars/Cosmic-Cyberpunk-Kitten-Theme
background            #00052E
foreground            #FFFFFF
selection_background  #0047AB
selection_foreground  #FFFFFF
cursor                #0047AB
# Black, Gray, Silver, White
color0                #00052E
color8                #A8B8CC
color7                #A8B8CC
color15               #FFFFFF
# Red
color1                #0047AB
color9                #0047AB
# Green
color2                #A8B8CC
color10               #FFFFFF
# Yellow
color3                #0047AB
color11               #A8B8CC
# Blue
color4                #0047AB
color12               #A8B8CC
# Purple
color5                #0047AB
color13               #A8B8CC
# Teal
color6                #0047AB
color14               #A8B8CC
